function [sV, sPsi] = gr_2d_surf_pot_wf(x, y, V, psi, red, orange, cyan, blue)
    sV = surf(x, y, V, ...
        'EdgeColor', 'none', ...
        'FaceColor', orange, ...
        'FaceAlpha', 0.5);
    
    hold on;
    
    sPsi = surf(x, y, psi, ...
        'EdgeColor', blue, ...
        'FaceColor', cyan, ...
        'FaceAlpha', 0.66);
    
    %zlim([0 z_max]);
    
    hold off;
end
